from typing import Dict

# Constants for chat template names
CHAT_TEMPLATE_CHATML = "chatml"
CHAT_TEMPLATE_VICUNA = "vicuna"
CHAT_TEMPLATE_MISTRAL = "mistral"

CHAT_TEMPLATES: Dict[str, str] = {
    CHAT_TEMPLATE_CHATML: (
        "{% for message in messages %}"
        "{% if message['role'] == 'user' %}"
        "{{'<|im_start|>user\n' + message['content'] + '<|im_end|>\n'}}"
        "{% elif message['role'] == 'assistant' %}"
        "{{'<|im_start|>assistant\n' + message['content'] + '<|im_end|>\n' }}"
        "{% else %}"
        "{{ '<|im_start|>system\n' + message['content'] + '<|im_end|>\n' }}"
        "{% endif %}"
        "{% endfor %}"
        "{% if add_generation_prompt %}"
        "{{ '<|im_start|>assistant\n' }}"
        "{% endif %}"
    ),
    CHAT_TEMPLATE_VICUNA: (
        "{{ bos_token }}"
        "{% if messages[0]['role'] == 'system' %}"
        "{{ messages[0]['content'] + ' ' }}"
        "{% set loop_messages = messages[1:] %}"
        "{% else %}"
        "{{ 'A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user\\'s questions.' + ' ' }}"
        "{% set loop_messages = messages %}"
        "{% endif %}"
        "{% for message in loop_messages %}"
        "{% if message['role'] == 'user' %}"
        "{{ 'USER: ' + message['content'] + ' ' }}"
        "{% elif message['role'] == 'assistant' %}"
        "{{ 'ASSISTANT: ' + message['content'] + eos_token }}"
        "{% else %}"
        "{{ raise_exception('Only user and assistant roles are supported!') }}"
        "{% endif %}"
        "{% endfor %}"
        "{% if add_generation_prompt %}"
        "{{ 'ASSISTANT:' }}"
        "{% endif %}"
    ),
    CHAT_TEMPLATE_MISTRAL: (
        "{{ bos_token }}"
        "{% if messages[0]['role'] == 'system' %}"
        "{% if messages[1]['role'] == 'user' %}"
        "{{ '[INST] ' + messages[0]['content'] + ' ' + messages[1]['content'] + ' [/INST]' }}"
        "{% set loop_messages = messages[2:] %}"
        "{% else %}"
        "{{ '[INST] ' + messages[0]['content'] + ' [/INST]' }}"
        "{% set loop_messages = messages[1:] %}"
        "{% endif %}"
        "{% else %}"
        "{% set loop_messages = messages %}"
        "{% endif %}"
        "{% for message in loop_messages %}"
        "{% if message['role'] == 'user' %}"
        "{{ '[INST] ' + message['content'] + ' [/INST]' }}"
        "{% elif message['role'] == 'assistant' %}"
        "{{ message['content'] + eos_token }}"
        "{% else %}"
        "{{ raise_exception('Only user and assistant roles are supported!') }}"
        "{% endif %}"
        "{% endfor %}"
    ),
}
